version: '2'

services:
  # https://github.com/google/cadvisor/blob/master/docs/running.md
  cadvisor:
    image: google/cadvisor
    ports:
    - "38080:8080"
    privileged: true
    restart: always
    volumes:
    - /:/rooffs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    # - /dev/disk/:/dev/disk:ro

  metering-exporter:
    command: 
    - export
    # - --meter=cadvisor=http://cadvisor:8080
    # - --collector=grpc=metering-collector:12305
    depends_on:
    - cadvisor
    environment: 
    - METERING_DRIVER_LIST=cadvisor=http://cadvisor:8080
    - METRICS_COLLECTOR_RPC=grpc=metering-collector:12305
    image: tangfeixiong/metering
    ports:
    - "12315:12315"
    - "12316:12316"
    # restart: always

  metering-collector:
    command: 
    - collect
    # - --storage=elasticsearch=http://elasticsearch:9200
    depends_on:
    - elasticsearch
    environment: 
    - METRICS_STORAGE_DRIVER=elasticsearch=http://elasticsearch:9200
    image: tangfeixiong/metering
    ports:
    - "12305:12305"
    - "12306:12306"
    # restart: always

  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    environment:
    - "discovery.type=single-node"
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    ports:
    - "39200:9200"
    - "39300:9300"