version: '2'

services:
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    environment:
    - "discovery.type=single-node"
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    ports:
    - "39200:9200"
    - "39300:9300"

  tracing-collector:
    command: 
    - jaeger-collector
    - --dependency-storage.type=elasticsearch
    - --span-storage.type=elasticsearch
    - --es.server-urls=http://elasticsearch:9200
    - --es.username=elastic
    - --es.password=changeme
    depends_on:
    - elasticsearch
    image: tangfeixiong/tracing
    ports:
    - "12305:12305"
    - "12306:12306"
    # restart: always
    
  tracing-agent:
    command: 
    - jaeger-agent
    # - --meter=cadvisor=http://cadvisor:8080
    # - --collector=grpc=metering-collector:12305
    image: tangfeixiong/tracing
    ports:
    - "12315:12315"
    - "12316:12316"
    # restart: always
    